version: 2.1

orbs:
  discord: antonioned/discord@0.1.0

jobs:
  test:
    docker:
      - image: cimg/node:10.24.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies- # 完全一致で見つからない場合用、最新キャッシュ取得

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

      - discord/status:
          fail_only: true
          failure_message: "Triggered User: **${CIRCLE_USERNAME}**\\nBranch: **${CIRCLE_BRANCH}**\\n\\nCircleCI テストに失敗しました。 JOB: **$CIRCLE_JOB**"
          webhook: "${DISCORD_WEBHOOK}"

workflows:
  version: 2
  ci:
    jobs:
      - test:
          context: kazuhito_m-products
